export type SchoolData = {
  id: number;
  ลำดับ: number;
  "ประมาณการติดตั้ง Solar cell": number;
  KW_PK: number;
  ตรวจสอบสถานที่: string;
  ชื่อโรงเรียน: string;
  ที่อยู่: string;
  ชื่อตำบล: string;
  ชื่ออำเภอ: string;
  ชื่อจังหวัด: string;
  รหัสไปรษณีย์: number;
  จำนวนนักเรียน: number;
  ภาค: string;
  สังกัด: string;
  เขต: string;
  กฟภ: string;
  อัตรา: string;
  CA: string;
  Status: string;
  "การติดต่อ 15%": number;
  "การเจรจา 30%": number;
  "ความสนใจ 30%": number;
  "กำลังติดตั้ง 25%": number;
  "Score 10คะแนน": number;
  "ความเข้าใจในโมเดล ESCO (10%)": number;
  "ระดับความร่วมมือของโรงเรียน (10%)": number;
  "การตัดสินใจและอำนาจภายใน (10%)": number;
  "ความพร้อมในการให้ข้อมูล (10%)": number;
  "การค้างค่าไฟฟ้า (10%)": number;

  "พื้นที่ติดตั้งที่มีอยู่ (10%)": number;
  "สภาพวัสดุมุงหลังคา (10%)": number;
  "สภาพโครงสร้าง (10%)": number;
  "จุดเชื่อมต่อและการเดินสายไฟ (10%)": number;
  "การเข้าถึงหน้างาน (10%)": number;
  รวมคะแนน: number;

  การดำเนินงาน: string;
  "E-mail": string;
  วันที่ดำเนินการ: string;
  activity?: string;
  ดำเนินการโดย: string;
  ชื่อผู้ประสานงานโรงเรียน: string;
  ตำแหน่ง: string;
  เบอร์ติดต่อผู้ประสานงาน: string;
  ชื่อผู้อำนวยการโรงเรียน: string;
  "เบอร์ติดต่อ ผอ.": string;
  "ค่าฟ้าเฉลี่ย/เดือน": string;
  "สถานะดำเนินการของ กฟภ.": string;
  ผู้ลงทุน: string;
  กลุ่มขนาดติดตั้ง: string;
  ชื่อผู้ติดต่อสังกัดสถานศึกษา: string;
  เบอร์โทรองค์กรสังกัดสถานศึกษา: string;
  เลขที่: string;
  วันที่: string;
  "เลขที่ ศธ.": string;
  วันที่ตอบกลับ: string;
  Simulation: string;
  ข้อเสนอโครงการ: string;
  "ข้อเสนอโครงการที่ออกจาก PEA": string;
  PEA: number;
  Focus: string;
  อาจารย์โจ้: string;
  check: string;
  Latitude: number;
  Longitude: number;
  chk: string;
  statusArr: string;
  activityArr: string;
  meterArr: string;
  หมายเหตุของโรงเรียน: string;
  หมายเหตุของพื้นที่: string;
  เลขที่หนังสือ: string;
  วันที่หนังสือ: string;
  "เลขที่ ศธ ข้อเสนอ": string;
  วันที่ข้อเสนอ: string;
  เลขที่ใบปะหน้า: string;
  วันที่ใบปะหน้า: string;
  รวมKW_PK: string;
  "link ข้อเสนอโครงการ": string;
  "link หนังสือเชิญ": string;
  "link หนังสือตอบรับข้อเสนอ": string;

  meterArrObject: { rate: string; ca: string; kw_pk: string }[];
  statusArrObject: { status: string; date?: string }[];
  activityArrObject: { activity: string; date?: string }[];
};

export type eventProps = {
  id?: number;
  team: string;
  title: string;
  description: string | null;
  school_id: number;
  date: string;
  schoolData?: SchoolData;
};
