export type SchoolData = {
  id: number;
  ลำดับ: number;
  "ประมาณการติดตั้ง Solar cell": number;
  KW_PK: number;
  ชื่อโรงเรียน: string;
  ที่อยู่: string;
  ชื่อตำบล: string;
  ชื่ออำเภอ: string;
  ชื่อจังหวัด: string;
  รหัสไปรษณีย์: number;
  จำนวนนักเรียน: number;
  ภาค: string;
  สังกัด: string;
  เขต: string;
  "กฟภ.": string;
  อัตรา: number;
  CA: number;
  Status: string;
  "การติดต่อ 15%": number;
  "การเจรจา 30%": number;
  "ความสนใจ 30%": number;
  "กำลังติดตั้ง 25%": number;
  "Score 10คะแนน": number;
  การดำเนินงาน: string;
  "E-mail": string;
  วันที่ดำเนินการ: string;
  activity?: string;
  ดำเนินการโดย: string;
  ชื่อผู้ประสานงานโรงเรียน: string;
  ตำแหน่ง: string;
  เบอร์ติดต่อผู้ประสานงาน: string;
  ชื่อผู้อำนวยการโรงเรียน: string;
  "เบอร์ติดต่อ ผอ.": string;
  "ค่าฟ้าเฉลี่ย/เดือน": string;
  "สถานะดำเนินการของ กฟภ.": string;
  ผู้ลงทุน: string;
  กลุ่มขนาดติดตั้ง: string;
  ชื่อผู้ติดต่อสังกัดสถานศึกษา: string;
  เบอร์โทรองค์กรสังกัดสถานศึกษา: string;
  เลขที่: string;
  วันที่: string;
  "เลขที่ ศธ.": string;
  วันที่ตอบกลับ: string;
  Simulation: string;
  ข้อเสนอโครงการ: string;
  "ข้อเสนอโครงการที่ออกจาก PEA": string;
  PEA: number;
  Focus: string;
  อาจารย์โจ้: string;
  check: string;
  Latitude: number;
  Longitude: number;
  chk: string;
};

export type eventProps = {
  id?: number;
  team: string;
  title: string;
  description: string | null;
  school_id: number;
  date: string;
  schoolData?: SchoolData;
};
