[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"